version: 4.0.0
variant: cyberpunk
logo:
    text: 不住斋札记
head:
    favicon: /img/github-s.png
    meta:
        - 'name=theme-color;content=#123456'
        - 'name=generator;content="Hexo 4.2.0"'
manifest:
    # Name of the web application (default to the site title)
    name: Icaurs - Hexo Theme
    # The displayed name of the web application
    # when there is not enough space to display full name
    short_name: Icarus
    # The start URL of the web application
    start_url: https://ppoffice.github.io/
    # The default theme color for the application
    theme_color: "#3273dc"
    # A placeholder background color for the application page to display
    # before its stylesheet is loaded
    background_color: "#3273dc"
    # The preferred display mode for the website
    display: standalone
    # Image files that can serve as application icons for different contexts
    icons:
        -
            # The path to the image file
            src: icons/touch-icon-iphone.png
            # A string containing space-separated image dimensions
            sizes: 144x144
            # A hint as to the media type of the image (optional)
            type: image/png
        -
            src: icons/touch-icon-ipad.png
            sizes: 152x152
        -
            src: icon/logo.ico
            sizes: 72x72 96x96 128x128 256x256
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Links to be shown on the right of the navigation bar
    links:
        GitHub: 'https://github.com'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'




